export {
  useInviteLink,
  useFamilyCode,
  useMyParentLinks,
  useGenerateInviteLink,
  useRegenerateFamilyCode,
  useRemoveParentLink,
  useValidateInviteCode,
  useLinkedChildren,
  useParentRegister,
  useLinkByFamilyCode,
  useAdminParentLinks,
  useCreateAdminParentLink,
  useUpdateAdminParentLinkStatus,
  useDeleteAdminParentLink,
} from "./parents.queries";
export type {
  ParentLink,
  InviteLinkResponse,
  FamilyCodeResponse,
  ParentRegisterRequest,
  InviteDetails,
  ChildProgress,
  LinkByCodeRequest,
  LinkByCodeResponse,
  AdminParentLink,
  CreateParentLinkRequest,
  UpdateParentLinkStatusRequest,
  AdminParentLinksResponse,
} from "./parents.types";
