export enum UniversityType {
  GOVERNMENT = 'GOVERNMENT',
  PRIVATE = 'PRIVATE',
  DEEMED = 'DEEMED',
  AUTONOMOUS = 'AUTONOMOUS',
}

export enum UniversityStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum ECFMGStatus {
  APPROVED = 'APPROVED',
  NOT_APPROVED = 'NOT_APPROVED',
  PENDING = 'PENDING',
}

export enum UniversityDocType {
  BROCHURE = 'BROCHURE',
  PROSPECTUS = 'PROSPECTUS',
  RECOGNITION_CERTIFICATE = 'RECOGNITION_CERTIFICATE',
  AFFILIATION_DOCUMENT = 'AFFILIATION_DOCUMENT',
  DEGREE_SAMPLE = 'DEGREE_SAMPLE',
  FEE_STRUCTURE = 'FEE_STRUCTURE',
  ADMISSION_FORM = 'ADMISSION_FORM',
  HOSTEL_RULES = 'HOSTEL_RULES',
  ANTI_RAGGING_POLICY = 'ANTI_RAGGING_POLICY',
  AGREEMENT = 'AGREEMENT',
}

