# session-end.ps1
# Run at end of each OpenCode session to document progress

$SESSION_DATE = Get-Date -Format "yyyy-MM-dd"
$SESSION_FILE = ".opencode/sessions/${SESSION_DATE}-session.md"
$TODO_FILE = ".opencode/TODO.md"

# Ensure sessions directory exists
if (!(Test-Path ".opencode\sessions")) {
    New-Item -ItemType Directory -Path ".opencode\sessions" -Force | Out-Null
}

# Get git info
$LAST_COMMIT = git log -1 --oneline
$BRANCH = git branch --show-current
$CHANGES = git status --short

# Create session file
$content = @"
# Session: $SESSION_DATE

### Last Commit
- ``$LAST_COMMIT``
- Branch: ``$BRANCH``

### Files Changed This Session
``````
$CHANGES
``````

### Key Accomplishments
- [ ] Add accomplishments here

### Next Steps
- See .opencode/TODO.md for remaining work

---
*Auto-generated by session-end script*
"@

$content | Out-File -FilePath $SESSION_FILE -Encoding utf8
Write-Output "Session saved to $SESSION_FILE"

# Update TODO last updated
if (Test-Path $TODO_FILE) {
    $todo = Get-Content $TODO_FILE -Raw
    $todo = $todo -replace '\*\*Last Updated:\*\*.*', "**Last Updated:** $SESSION_DATE"
    $todo | Out-File -FilePath $TODO_FILE -Encoding utf8
    Write-Output "TODO.md updated"
}

Write-Output "`nSession tracking complete!"
